package com.willu.model;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class tb_user {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Id
     *
     * @mbggenerated Thu Oct 13 10:18:29 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Username
     *
     * @mbggenerated Thu Oct 13 10:18:29 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbggenerated Thu Oct 13 10:18:29 CST 2016
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Id
     *
     * @return the value of tb_user.Id
     *
     * @mbggenerated Thu Oct 13 10:18:29 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Id
     *
     * @param id the value for tb_user.Id
     *
     * @mbggenerated Thu Oct 13 10:18:29 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Username
     *
     * @return the value of tb_user.Username
     *
     * @mbggenerated Thu Oct 13 10:18:29 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Username
     *
     * @param username the value for tb_user.Username
     *
     * @mbggenerated Thu Oct 13 10:18:29 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbggenerated Thu Oct 13 10:18:29 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbggenerated Thu Oct 13 10:18:29 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}